---
# Add tools for code quality

- name: Create tmp directory
  file:
    path: "{{ pypi_cache }}"
    state: directory
    mode: 0777

- name: Install dependencies
  package:
    name: "{{ quality_tools }}"
    state: present
    update_cache: true

- name: Install /etc/profile.d/proxy.sh
  when: proxy_host is defined
  template:
    src: proxy.sh.j2
    dest: /etc/profile.d/proxy.sh
    owner: root
    group: root
    mode: 0644

- name: Install /etc/pip.conf
  when: pypi_trusted_host is defined
  template:
    src: pip.conf.j2
    dest: /etc/pip.conf
    owner: root
    group: root
    mode: 0644

- name: Copy requirements
  become: true
  template:
    src: "{{ item }}"
    dest: /tmp/
    mode: 0644
  loop:
    - requirements.txt
    - requirements.yml

- name: Create virtualenv
  become: true
  pip:
    virtualenv: /usr/local
    virtualenv_command: /bin/python3.8 -m venv
    virtualenv_site_packages: true
    name: wheel
    extra_args: "--cache-dir={{ pypi_cache }} -i {{ pypi_index }}"

- name: Install requirements
  become: true
  pip:
    requirements: /tmp/requirements.txt
    virtualenv: /usr/local
    extra_args: "--cache-dir={{ pypi_cache }} -i {{ pypi_index }}"
    state: "{{ desired_state | default('present', true) }}"

- name: Install collections
  become: true
  become_user: jenkins
  shell: |
    source /usr/local/bin/activate
    ansible-galaxy collection install -r /tmp/requirements.yml
  args:
    creates: /home/jenkins/.ansible/collections/ansible_collections/community/docker


...
