---

- name: Group hosts by distribution
  hosts: myhosts
  gather_facts: true
  tasks:
    - name: Create groups based on distro
      group_by:
        key: "{{ ansible_distribution }}"
- name: Do something to Ubuntu hosts
  hosts: Ubuntu
  tasks:
    - name: Install jdk and jre
      apt:
        name:
          - openjdk-11-jdk-headless
          - openjdk-11-jre-headless
- name: Do something else to CentOS hosts
  hosts: CentOS
  tasks:
    - name: Install jdk
      yum:
        name:
          - java-11-openjdk-headless
          - java-11-openjdk-devel
