#!/usr/bin/env ansible-playbook
---

- name: Hardened Centos 7
  hosts: all
  become: true

  vars:
    net_allow:
      - '192.168.0.0/16'

  roles:
    - {role: common, tags: common}
    - {role: epel, tags: epel}
    - {role: ansible-auditd, tags: auditd}
    - {role: nettime, tags: nettime}
    - {role: rsyslog, tags: syslog}
    - {role: crontab, tags: crontab}
    - {role: keybase, tags: keybase}
    - {role: gpg_agent, tags: gpg}
    - {role: tailscale, tags: tailscale}
