---

- name: restart sshd
  debug:
    msg: "checking /etc/ssh/sshd_config first"
  changed_when: true
  notify:
    - check sshd configuration
    - restart sshd - after config check

- name: check sshd configuration
  become: true
  command: '/usr/sbin/sshd -t'
  register: sshd_config
  changed_when: "sshd_config.rc != 0"

- name: restart sshd - after config check
  become: true
  service:
    name: sshd
    state: restarted

- name: goss
  debug:
    msg: "goss template changed"
  listen: goss
  tags:
    - ssh
