#!/usr/bin/env -S ansible-playbook -vv
---

- name: Provisioner
  hosts: all
  become: true
  gather_facts: true

  vars:
    crypto_policy: STRICT
    intended_user: vagrant

  roles:
    - ansible_book_ssh
...
