#!/usr/bin/env ansible-playbook
---

- name: chapter 9 playbook
  hosts: web
  gather_facts: false
  become: false

  tasks:

    - name: wait for web ssh daemon to be running
      wait_for:
        port: 22
        host: "{{ inventory_hostname }}"
        search_regex: OpenSSH

    - name: ping the host
      ping:

    - name: gather facts
      setup:

    - name: display eth1 ip-address
      debug:
        msg: "{{ ansible_eth1.ipv4.address }} {{ inventory_hostname }}"

- hosts: strategies
  connection: local
  strategy: free
  gather_facts: false
  tasks:
    - name: first task
      command: sleep "{{ sleep_seconds }}"
      changed_when: false

    - name: second task
      command: sleep "{{ sleep_seconds }}"
      changed_when: false

    - name: third task
      command: sleep "{{ sleep_seconds }}"
      changed_when: false
