---

- name: setup
  setup:

- name: include OS specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags:
    - linux

- name: print out operating system details
  debug:
    msg: >-
      os_family:
      {{ ansible_os_family }},
      distro:
      {{ ansible_distribution }}
      {{ ansible_distribution_version }},
      sshd_policy_file:
      {{ sshd_policy_file }}
  tags:
    - linux

- name: load crypto vars
  include_vars: "{{ crypto_settings }}"
  tags:
    - linux

- name: change ssh key to ed25519
  authorized_key:
    user: vagrant
    key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
    exclusive: true
  tags:
    - linux

- name: set permissions
  file:
    owner: root
    group: root
    path: "{{ sshd_policy_file }}"
    mode: "{{ sshd_policy_mode }}"
    state: touch
  tags:
    - linux

- name: improve SSHd Ciphers
  lineinfile:
    dest: "{{ sshd_policy_file }}"
    regexp: '^Ciphers'
    line: "Ciphers {{ Ciphers }}"
    state: present
  notify: restart sshd
  tags:
    - ciphers

- name: improve SSHd KexAlgorithms
  lineinfile:
    dest: "{{ sshd_policy_file }}"
    regexp: '^KexAlgorithms'
    line: "KexAlgorithms {{ KexAlgorithms }}"
    state: present
  notify: restart sshd
  tags:
    - kex

- name: improve SSHd MACs
  lineinfile:
    dest: "{{ sshd_policy_file }}"
    regexp: '^MACs'
    line: "MACs {{ MACs }}"
    state: present
  notify: restart sshd
  tags:
    - hostkey

- name: improve SSHd HostKeyAlgorithms
  lineinfile:
    dest: "{{ sshd_policy_file }}"
    regexp: '^HostKeyAlgorithms'
    line: "HostKeyAlgorithms {{ HostKeyAlgorithms }}"
    state: present
  notify: restart sshd
  tags:
    - hostkey

- name: check the ed25519 host key
  stat:
    path: /etc/ssh/ssh_host_ed25519_key
  register: ed25519

- name: generate ed25519 host key
  command: ssh-keygen -t ed25519 -f /etc/ssh/ssh_host_ed25519_key -N ""
  when:
    - not ed25519.stat.exists|bool
  notify: restart sshd
  changed_when: true

- name: set permissions
  file:
    path: /etc/ssh/ssh_host_ed25519_key
    mode: 0600

- name: configure ed25519 host key
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^HostKey /etc/ssh/ssh_host_ed25519_key'
    line: 'HostKey /etc/ssh/ssh_host_ed25519_key'
    insertbefore: '^# HostKey /etc/ssh/ssh_host_rsa_key'
    mode: 0600
    state: present
  notify: restart sshd

- name: disable weak host keys
  include_tasks: weak_keys.yml
  loop: "{{ weak_host_keys }}"

- name: check if /etc/ssh/moduli contains weak Diffie-Hellman moduli
  shell: awk '$5 < 2048' /etc/ssh/moduli
  register: sshd_register_moduli
  changed_when: false
  check_mode: false

- name: deactivate short Diffie-Hellman moduli
  when: sshd_register_moduli.stdout
  shell: "awk '$5 >= 2048' /etc/ssh/moduli > /etc/ssh/moduli.safe && mv -f /etc/ssh/moduli.safe /etc/ssh/moduli"
  tags:
    - skip_ansible_lint
