---

- name: Uninstall choco packages
  win_chocolatey:
    name: "{{ uninstall_choco_packages }}"
    state: absent
    force: true

- name: Install Google Chrome
  win_chocolatey:
    name: googlechrome
    state: present

- name: Create local directory
  win_file:
    path: "{{ win_local_dir }}"
    state: directory


