---
- name: Show return value of stat module
  hosts: ubuntu
  gather_facts: true
  become: true
  tasks:
    - name: Determine file properties
      stat:
        path: /etc/ssh/sshd_config
      register: result

    - name: Display result.stat
      debug: var=result.stat
...
