#!/usr/bin/env ansible-playbook
---
- name: provision servers
  hosts: all
  vars:
    crypto_settings: faster.yml
    install_goss: true
  roles:
    - {role: goss}
    - {role: dependencies, tags: dependencies}

  post_tasks:

    - name: ping hosts
      ping:

    - name: create locale
      become: true
      command: localedef -i en_US -f UTF-8 en_US.UTF-8
      when: ansible_distribution == 'Debian'

    - name: create locale
      become: true
      command: localectl set-locale LANG=en_US.UTF-8
      when: ansible_distribution == 'Fedora'

    - name: install Goss
      include_role:
        name: goss
        tasks_from: install
      tags:
        - goss

    - name: improve ssh configuration
      include_role:
        name: ssh
      tags:
        - ssh

    - name: flush handlers
      meta: flush_handlers

    - name: run Goss tests
      include_role:
        name: goss
        tasks_from: tests
      tags:
        - goss
